baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Never Stop Study!!!'
theme = 'hugo-xmin-zpf'

menu
  main
    - name: Home
      url: ""
      weight: 1
    - name: Categories
      url: "categories/"
      weight: 2
    - name: About
      url: "about/"
      weight: 3
